language: java
jdk: openjdk8
script: mvn test -P android
addons:
  browserstack:
    username: adityaroshandemo_NODHGL
    access_key: ayGc3m89Sj8dsDUNqQLu
    app_path: cucumber-testng-browerstack/src/test/java/WikipediaSample.apk
